import { NextRequest, NextResponse } from 'next/server';
import { getAdminAuth, getAdminFirestore } from '../../../../lib/firebaseAdmin';

/**
 * POST /api/license-requests/approve
 *
 * "Approve" now means "mark as shared" — the key was already generated by the
 * admin desktop and is already stored in both the request and the license docs.
 * This endpoint simply flips the request status to 'approved' (shared) and, if
 * a matching license doc exists, marks it 'active'.
 *
 * Body: { idToken, requestId }
 */
export async function POST(req: NextRequest) {
  try {
    const auth = getAdminAuth();
    const db = getAdminFirestore();

    const body = await req.json();
    const { idToken, requestId } = body;

    if (!idToken || !requestId) {
      return NextResponse.json(
        { ok: false, error: 'idToken and requestId are required' },
        { status: 400 }
      );
    }

    const decoded = await auth.verifyIdToken(idToken);
    const adminUid = decoded.uid;

    const requestRef = db.collection('licenseRequests').doc(requestId);
    const requestSnap = await requestRef.get();

    if (!requestSnap.exists) {
      return NextResponse.json(
        { ok: false, error: 'License request not found' },
        { status: 404 }
      );
    }

    const requestData = requestSnap.data() as {
      status?: string;
      licenseId?: string;
    };

    // Allow marking as shared from 'desktop_generated' or 'pending' statuses
    const allowedStatuses = ['pending', 'desktop_generated'];
    if (requestData.status && !allowedStatuses.includes(requestData.status)) {
      return NextResponse.json(
        { ok: false, error: `Request already ${requestData.status}` },
        { status: 400 }
      );
    }

    const nowIso = new Date().toISOString();

    // Mark the request as approved/shared
    await requestRef.update({
      status: 'approved',
      handledBy: adminUid,
      handledAt: nowIso,
    });

    // If there is a linked license doc, mark it active and record share time
    if (requestData.licenseId) {
      const licenseRef = db.collection('licenses').doc(requestData.licenseId);
      const licenseSnap = await licenseRef.get();
      if (licenseSnap.exists) {
        await licenseRef.update({
          status: 'active',
          sharedAt: nowIso,
          sharedBy: adminUid,
        });
      }
    }

    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error('approve route error:', error);
    return NextResponse.json(
      { ok: false, error: 'Failed to approve request' },
      { status: 500 }
    );
  }
}
