/** @type {import('tailwindcss').Config} */

const withOpacityValue =
  (cssVariable) =>
  ({ opacityValue } = {}) => {
    if (opacityValue === undefined) {
      return `rgb(var(${cssVariable}) / 1)`;
    }
    return `rgb(var(${cssVariable}) / ${opacityValue})`;
  };

module.exports = {
  darkMode: 'class',
  content: ['./src/renderer/**/*.{js,jsx,ts,tsx}', './src/renderer/index.html'],
  theme: {
    extend: {
      colors: {
        'dark-teal': '#145f55',
        emerald: {
          50: withOpacityValue('--color-emerald-50'),
          100: withOpacityValue('--color-emerald-100'),
          200: withOpacityValue('--color-emerald-200'),
          300: withOpacityValue('--color-emerald-300'),
          400: withOpacityValue('--color-emerald-400'),
          500: withOpacityValue('--color-emerald-500'),
          600: withOpacityValue('--color-emerald-600'),
          700: withOpacityValue('--color-emerald-700'),
          800: withOpacityValue('--color-emerald-800'),
          900: withOpacityValue('--color-emerald-900'),
          950: withOpacityValue('--color-emerald-950'),
        },
        green: {
          50: withOpacityValue('--color-green-50'),
          100: withOpacityValue('--color-green-100'),
          200: withOpacityValue('--color-green-200'),
          300: withOpacityValue('--color-green-300'),
          400: withOpacityValue('--color-green-400'),
          500: withOpacityValue('--color-green-500'),
          600: withOpacityValue('--color-green-600'),
          700: withOpacityValue('--color-green-700'),
          800: withOpacityValue('--color-green-800'),
          900: withOpacityValue('--color-green-900'),
          950: withOpacityValue('--color-green-950'),
        },
        lime: {
          50: withOpacityValue('--color-lime-50'),
          100: withOpacityValue('--color-lime-100'),
          200: withOpacityValue('--color-lime-200'),
          300: withOpacityValue('--color-lime-300'),
          400: withOpacityValue('--color-lime-400'),
          500: withOpacityValue('--color-lime-500'),
          600: withOpacityValue('--color-lime-600'),
          700: withOpacityValue('--color-lime-700'),
          800: withOpacityValue('--color-lime-800'),
          900: withOpacityValue('--color-lime-900'),
          950: withOpacityValue('--color-lime-950'),
        },
        blue: {
          50: withOpacityValue('--color-blue-50'),
          100: withOpacityValue('--color-blue-100'),
          200: withOpacityValue('--color-blue-200'),
          300: withOpacityValue('--color-blue-300'),
          400: withOpacityValue('--color-blue-400'),
          500: withOpacityValue('--color-blue-500'),
          600: withOpacityValue('--color-blue-600'),
          700: withOpacityValue('--color-blue-700'),
          800: withOpacityValue('--color-blue-800'),
          900: withOpacityValue('--color-blue-900'),
          950: withOpacityValue('--color-blue-950'),
        },
        red: {
          50: withOpacityValue('--color-red-50'),
          100: withOpacityValue('--color-red-100'),
          200: withOpacityValue('--color-red-200'),
          300: withOpacityValue('--color-red-300'),
          400: withOpacityValue('--color-red-400'),
          500: withOpacityValue('--color-red-500'),
          600: withOpacityValue('--color-red-600'),
          700: withOpacityValue('--color-red-700'),
          800: withOpacityValue('--color-red-800'),
          900: withOpacityValue('--color-red-900'),
          950: withOpacityValue('--color-red-950'),
        },
        yellow: {
          50: withOpacityValue('--color-yellow-50'),
          100: withOpacityValue('--color-yellow-100'),
          200: withOpacityValue('--color-yellow-200'),
          300: withOpacityValue('--color-yellow-300'),
          400: withOpacityValue('--color-yellow-400'),
          500: withOpacityValue('--color-yellow-500'),
          600: withOpacityValue('--color-yellow-600'),
          700: withOpacityValue('--color-yellow-700'),
          800: withOpacityValue('--color-yellow-800'),
          900: withOpacityValue('--color-yellow-900'),
          950: withOpacityValue('--color-yellow-950'),
        },
        orange: {
          50: withOpacityValue('--color-orange-50'),
          100: withOpacityValue('--color-orange-100'),
          200: withOpacityValue('--color-orange-200'),
          300: withOpacityValue('--color-orange-300'),
          400: withOpacityValue('--color-orange-400'),
          500: withOpacityValue('--color-orange-500'),
          600: withOpacityValue('--color-orange-600'),
          700: withOpacityValue('--color-orange-700'),
          800: withOpacityValue('--color-orange-800'),
          900: withOpacityValue('--color-orange-900'),
          950: withOpacityValue('--color-orange-950'),
        },
        purple: {
          50: withOpacityValue('--color-purple-50'),
          100: withOpacityValue('--color-purple-100'),
          200: withOpacityValue('--color-purple-200'),
          300: withOpacityValue('--color-purple-300'),
          400: withOpacityValue('--color-purple-400'),
          500: withOpacityValue('--color-purple-500'),
          600: withOpacityValue('--color-purple-600'),
          700: withOpacityValue('--color-purple-700'),
          800: withOpacityValue('--color-purple-800'),
          900: withOpacityValue('--color-purple-900'),
          950: withOpacityValue('--color-purple-950'),
        },
        indigo: {
          50: withOpacityValue('--color-indigo-50'),
          100: withOpacityValue('--color-indigo-100'),
          200: withOpacityValue('--color-indigo-200'),
          300: withOpacityValue('--color-indigo-300'),
          400: withOpacityValue('--color-indigo-400'),
          500: withOpacityValue('--color-indigo-500'),
          600: withOpacityValue('--color-indigo-600'),
          700: withOpacityValue('--color-indigo-700'),
          800: withOpacityValue('--color-indigo-800'),
          900: withOpacityValue('--color-indigo-900'),
          950: withOpacityValue('--color-indigo-950'),
        },
        gray: {
          50: withOpacityValue('--color-gray-50'),
          100: withOpacityValue('--color-gray-100'),
          200: withOpacityValue('--color-gray-200'),
          300: withOpacityValue('--color-gray-300'),
          400: withOpacityValue('--color-gray-400'),
          500: withOpacityValue('--color-gray-500'),
          600: withOpacityValue('--color-gray-600'),
          700: withOpacityValue('--color-gray-700'),
          800: withOpacityValue('--color-gray-800'),
          900: withOpacityValue('--color-gray-900'),
          950: withOpacityValue('--color-gray-950'),
        },
        white: withOpacityValue('--color-white'),
        black: withOpacityValue('--color-black'),
      },
      animation: {
        'gradient-shift': 'gradientShift 15s ease infinite',
        float: 'float 20s ease-in-out infinite',
        'float-circle': 'floatCircle 15s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 1s ease 0.3s both',
        'title-reveal': 'titleReveal 1.2s ease 0.5s both',
        'slide-in-left': 'slideInLeft 0.8s ease both',
        'slide-in-right': 'slideInRight 0.8s ease both',
        'fade-in': 'fadeIn 1s ease both',
        shimmer: 'shimmer 3s ease-in-out infinite',
      },
      keyframes: {
        gradientShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(50px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-30px, 30px) scale(0.9)' },
        },
        floatCircle: {
          '0%, 100%': {
            transform: 'translate(0, 0) rotate(0deg)',
            opacity: '0.3',
          },
          '50%': {
            transform: 'translate(30px, -30px) rotate(180deg)',
            opacity: '0.6',
          },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        titleReveal: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          from: { opacity: '0', transform: 'translateX(-50px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(50px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      backgroundSize: {
        '400%': '400% 400%',
      },
    },
  },
  plugins: [],
};
