import { NextRequest, NextResponse } from 'next/server';
import { getAdminFirestore } from '../../../../lib/firebaseAdmin';

/**
 * POST /api/licenses/register-from-desktop
 *
 * Called by the admin desktop app after it has generated a 14-char license key
 * locally. This endpoint stores the key in Firestore so the web admin can see
 * it and share it. The key itself is NOT generated here — it arrives ready-made.
 *
 * Body: {
 *   licenseKey: string,       // 14-char key generated by the desktop
 *   pharmacyName: string,
 *   email: string,
 *   phone: string,
 *   doctorName?: string | null,
 *   address?: string | null,
 *   city?: string | null,
 *   country?: string | null,
 * }
 */
export async function POST(req: NextRequest) {
  try {
    const db = getAdminFirestore();

    const body = (await req.json()) as {
      licenseKey?: string;
      pharmacyName?: string;
      email?: string;
      phone?: string;
      doctorName?: string | null;
      address?: string | null;
      city?: string | null;
      country?: string | null;
    };

    const { licenseKey, pharmacyName, email, phone } = body;

    if (!licenseKey || !pharmacyName || !email || !phone) {
      return NextResponse.json(
        { ok: false, error: 'licenseKey, pharmacyName, email, and phone are required' },
        { status: 400 }
      );
    }

    // Normalize key (strip spaces/hyphens, uppercase)
    const normalizedKey = licenseKey.replace(/[^A-Za-z0-9]/g, '').toUpperCase();

    // Prevent duplicate registrations
    const existing = await db
      .collection('licenses')
      .where('licenseKey', '==', normalizedKey)
      .limit(1)
      .get();

    if (!existing.empty) {
      return NextResponse.json(
        { ok: false, error: 'This license key is already registered' },
        { status: 409 }
      );
    }

    const now = new Date();
    const nowIso = now.toISOString();

    // validFrom = now, validUntil = now + 6 months (mirrors desktop activation)
    const validUntil = new Date(now);
    validUntil.setMonth(validUntil.getMonth() + 6);

    // Write to licenseRequests (so it appears on the Requests page)
    const requestRef = await db.collection('licenseRequests').add({
      pharmacyName,
      email,
      phone,
      doctorName: body.doctorName ?? null,
      address: body.address ?? null,
      city: body.city ?? null,
      country: body.country ?? null,
      status: 'desktop_generated',
      licenseKey: normalizedKey,
      createdAt: nowIso,
      requestedAt: nowIso,   // needed for the Requests page orderBy('requestedAt')
      source: 'desktop',
    });

    // Write to licenses (so it appears on the Licenses page)
    const licenseRef = await db.collection('licenses').add({
      pharmacyName,
      email,
      phone,
      doctorName: body.doctorName ?? null,
      address: body.address ?? null,
      city: body.city ?? null,
      country: body.country ?? null,
      licenseKey: normalizedKey,
      shortKey: normalizedKey,
      validFrom: nowIso,
      validUntil: validUntil.toISOString(),
      status: 'pending_share',
      requestId: requestRef.id,
      createdAt: nowIso,
      source: 'desktop',
    });

    // Link licenseId back to the request
    await requestRef.update({ licenseId: licenseRef.id });

    return NextResponse.json({ ok: true, id: licenseRef.id, requestId: requestRef.id });
  } catch (error) {
    console.error('register-from-desktop error:', error);
    return NextResponse.json(
      { ok: false, error: 'Failed to register license key' },
      { status: 500 }
    );
  }
}
